languageCode = "en-us"
title = "twobiers"
theme = "congo"
defaultcontentlanguage = "en"

pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableRobotsTXT = true

[pagination]
  pagerSize = 20

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"]

[frontmatter]
	date = [":filename", ":default", ":fileModTime"]