languageCode = "en-us"
title = "twobiers"
defaultcontentlanguage = "en"

pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableRobotsTXT = true

[params.author]
  name = "Tobi"
  bio = "🥒"
  image = "img/avatar.jpg"
  links = [
    { github = "https://github.com/twobiers" },
    { spotify = "https://open.spotify.com/twobiers" }
  ]

[pagination]
  pagerSize = 20

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"]

[frontmatter]
	date = [":filename", ":default", ":fileModTime"]