description = "Web Page Of Stupid Random Stuff"
homepage.layout = "profile"

colorScheme = "avocado"
dateFormat = "2006-02-01"

[author]
  name = "Tobi"
  bio = "🥒"
  image = "img/avatar.jpg"
  links = [
    { github = "https://github.com/twobiers" },
    { spotify = "https://open.spotify.com/twobiers" }
  ]

[article]
    showComments = true

[entry]
    meta = ["date", "categories", "tags"]

enableCodeCopy = true