description = "Web Page Of Stupid Random Stuff"
homepage.layout = "profile"

colorScheme = "cherry"
dateFormat = "2006-02-01"

[article]
    showComments = true

[entry]
    meta = ["date", "categories", "tags"]

enableCodeCopy = true