baseURL = 'https://twobiers.github.io/'
languageCode = "en-us"
title = "Twobiers"
theme = "binario"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[Author]
  name = "Tobi"
  bio = "🥒"
  avatar = "images/avatar.jpg"

[params]
  description = "Web Page Of Stupid Random Stuff"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[Params.Social]
  github = "twobiers"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "/posts"
[[menu.main]]
  name = "About"
  weight = 2
  url = "/about"